In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.1.1


In [6]:
x = np.zeros(10)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
x = np.array([1,2,3,4,5,6,7])

print("The size of the array: ",x.size)
print("The memory size of the array: ",x.itemsize) #in bytes


The size of the array:  7
The memory size of the array:  8


In [8]:
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [9]:
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

In [12]:
x = np.zeros(10)
x[4] = 1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
y = np.arange(10,50)
print(y)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
new_array = np.flip(y)
print("Reversed array:",new_array)


Reversed array: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
res = y[::-1]
print(res)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [23]:
a = np.random.randint(8, size = (3,3))
print(a)


[[3 1 6]
 [4 0 5]
 [6 1 3]]


#Finding indices of non zero elements

In [30]:
a = [1,2,0,0,4,0]
np.nonzero(a)




(array([0, 1, 4]),)

In [31]:
#3x3 identity matrix
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
#A 3x3x3 array with random values
a = np.random.random((3,3,3))
print(a)


[[[0.99783217 0.38236495 0.48582311]
  [0.66293289 0.13274363 0.06425498]
  [0.6467598  0.93599196 0.74078318]]

 [[0.78109241 0.77028699 0.60589247]
  [0.86632896 0.35190543 0.4542775 ]
  [0.72160335 0.38276569 0.52243019]]

 [[0.7986729  0.41448806 0.15571447]
  [0.24186594 0.79317107 0.52288744]
  [0.82021866 0.3246059  0.83523468]]]


In [53]:
#A 10x10 array with random values
a = np.random.random((10,10))
print(a)
print(np.max(a))
print(np.min(a))

[[0.28896368 0.81321624 0.87895106 0.35035337 0.0194941  0.32891554
  0.44811146 0.60674702 0.41067043 0.88152952]
 [0.53289587 0.47633291 0.99730408 0.72653124 0.25724415 0.65628696
  0.21271193 0.21754077 0.51170882 0.00646043]
 [0.08317203 0.40777453 0.65056483 0.55450883 0.02889118 0.03267745
  0.58864138 0.60756871 0.54611958 0.9820433 ]
 [0.35145466 0.07184553 0.34445724 0.3547087  0.36270623 0.3901784
  0.06816546 0.04054698 0.45119464 0.73350282]
 [0.08774947 0.68372103 0.97146798 0.85155761 0.7851839  0.76732229
  0.28327171 0.02032494 0.49365196 0.71567401]
 [0.95153335 0.20013025 0.0533305  0.66068792 0.86480421 0.90393162
  0.22688469 0.46613076 0.28037927 0.12956294]
 [0.97923073 0.29545933 0.03391912 0.823311   0.73804494 0.58234251
  0.54042531 0.74427734 0.97104169 0.70447425]
 [0.45426524 0.78511247 0.88690955 0.48985355 0.71355704 0.72296444
  0.18869417 0.25350069 0.46755839 0.25487622]
 [0.14116881 0.3205995  0.11576306 0.17529176 0.3997932  0.95064865
  0.09873659 

In [60]:
#A random vector of size 30
a = np.random.random(30)
m = a.mean()
print(m)



0.47768555978891314


In [61]:
#A 2D array with 1 on the border and 0 inside
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
